#!/usr/bin/env bash

################################################################################
#
# Copies the audit.log from the first oauth-server found. Ideally there is only
# one replica, or the script gets extended for multi replicas.
#
################################################################################

FILENAME=$PWD/$(date +%Y-%m-%d)-oauth-server-audit
FILE=$FILENAME.json
FILE_MINIFIED=$FILENAME.min.json

kubectl get pods -n openshift-authentication \
    | tail -n1 \
    | awk '{ print $1 }' \
    | xargs -i kubectl cp -n openshift-authentication \
        {}:var/log/oauth-server/audit.log \
        $FILE_MINIFIED \
    && jq < $FILE_MINIFIED > $FILE
