#!/usr/bin/env bash

###############################################################################
#
# Prints open PRs from Team Members in OpenShift
#
###############################################################################

TEAM_FILTER="-e s-urbaniak -e stlaz -e slaskawi -e emilym1 -e ibihim"
OPENSHIFT_REPOS=$(gh repo list openshift \
    --json nameWithOwner --jq '.[].nameWithOwner' \
    --limit 1000 | sort\
)

BREAK="################################################################################"

for REPO in $OPENSHIFT_REPOS
do
    PR_LIST=$(gh pr list  \
        --repo $REPO --limit 1000 \
        --json 'author,title,url' --jq '.[] | "\(.author.login)*\(.title)*\(.url)"' \
        | rg -i $TEAM_FILTER \
        | column -t -s '*' \
    )

    if [[ -n $PR_LIST ]]
    then
        printf '\n%s\n#\n# %s\n#\n%s\n\n' $BREAK $REPO $BREAK
        printf "$PR_LIST\n"
    fi
done
