apiVersion: v1
kind: Namespace
metadata:
  name: rbac-test
---
apiVersion: v1
data:
  firstname: a3J6eXN6dG9m
kind: Secret
metadata:
  name: kostrows-secrets
  namespace: rbac-test
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: secret-reader
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["kostrows-secrets"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-secrets
  namespace: rbac-test
subjects:
- kind: User
  name: kostrows
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io
